// Generated by scripts/recovery/generate-shims.mjs — a compat shim: no logic, only the owner's exports under the old names.
export { defaultClock, toReactive } from "obix-core-reactive";
export type { Clock, ReactiveFactory, ReactiveInstance, Subscriber } from "obix-core-reactive";
